server.port=8082
spring.datasource.url=jdbc:postgresql://localhost:5434/emailDb
spring.datasource.username=emailDb
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.rabbitmq.address=amqps://kgcuixkc:Uz3SFQux4zK1RMB4KlbMFCdu515OxTg0@chameleon.lmq.cloudamqp.com/kgcuixkc
broker.queue.email.name=default.email
spring.rabbitmq.ssl.enabled=true